# Generated by Django 3.2.6 on 2021-08-12 16:21

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20210811_2048'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='links',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.TextField(blank=True), blank=True, default=list, size=None),
        ),
        migrations.AlterField(
            model_name='note',
            name='step_one_iterations',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.TextField(blank=True), blank=True, default=list, size=None),
        ),
        migrations.AlterField(
            model_name='note',
            name='step_two_iterations',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.TextField(blank=True), blank=True, default=list, size=None),
        ),
    ]
