# Generated by Django 3.2.6 on 2021-08-13 13:57

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20210812_1621'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='links',
            field=django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.TextField(blank=True), size=2), blank=True, default=list, size=None),
        ),
    ]
