# Generated by Django 3.2.6 on 2021-08-15 23:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_subject'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Subject',
            new_name='Folder',
        ),
    ]
