# Generated by Django 3.2.6 on 2021-08-16 12:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_note_subject'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='note',
            name='subject',
        ),
        migrations.AddField(
            model_name='note',
            name='folder',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='folder_notes', to='main.folder'),
        ),
    ]
