# Generated by Django 3.2.6 on 2021-08-21 11:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_auto_20210816_1212'),
    ]

    operations = [
        migrations.CreateModel(
            name='Iteration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=84)),
                ('text', models.TextField(blank=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='note',
            name='links',
        ),
        migrations.RemoveField(
            model_name='note',
            name='step_one_iterations',
        ),
        migrations.RemoveField(
            model_name='note',
            name='step_two_iterations',
        ),
        migrations.AlterField(
            model_name='folder',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='folders', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='note',
            name='owner',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Link',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=64)),
                ('href', models.TextField(blank=True)),
                ('note', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='links', to='main.note')),
                ('which_iteration', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='links', to='main.iteration')),
            ],
        ),
        migrations.AddField(
            model_name='iteration',
            name='note_step_one',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='step_one_iterations', to='main.note'),
        ),
        migrations.AddField(
            model_name='iteration',
            name='note_step_two',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='step_two_iterations', to='main.note'),
        ),
    ]
