# Generated by Django 3.2.6 on 2021-08-21 18:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_auto_20210821_1206'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='link',
            name='note',
        ),
        migrations.AlterField(
            model_name='iteration',
            name='note_step_one',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='step_one_iterations', to='main.note'),
        ),
        migrations.AlterField(
            model_name='iteration',
            name='note_step_two',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='step_two_iterations', to='main.note'),
        ),
    ]
