# Generated by Django 3.2.6 on 2021-08-24 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_auto_20210821_1810'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='sub',
            field=models.CharField(default=None, max_length=64, null=True),
        ),
    ]
