# Generated by Django 3.2.6 on 2021-09-02 14:18

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_user_sub'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='created',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
