name: Django CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  run-tests:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres
        env:
          POSTGRES_PASSWORD: '1234'
          POSTGRES_USER: 'runner'
        # Set health checks to wait until postgres has started
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 
      uses: actions/setup-python@v2
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Setup postgres
      run: |
        sudo service postgresql start
        sudo -u postgres -i
        psql
        CREATE USER mario WITH PASSWORD '1234';
        ALTER USER mario WITH CREATEDB;
        \q
        exit
    - name: Run Tests
      run: |
        python manage.py test
