name: Django CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  run-tests:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 
      uses: actions/setup-python@v2
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Setup postgres
      run: |
        sudo -u postgres -i
        psql
        CREATE USER mario WITH PASSWORD '1234';
        ALTER USER mario WITH CREATEDB;
        \q
        exit
    - name: Run Tests
      run: |
        python manage.py test
